### ISSUE TITLE
repcred failure on processing alleles

### ISSUE THREAD

**Issue by bcorrie** [airr-community/rep-cred#27]
Creating a set of issues as I try repertoires from a bunch of different studies.

PRJNA752617, `repertoire_id = 613b7f3eadf6058ccd849076` on covid19-1.ireceptor.org
```
Rendering book in directory '.'


processing file: _main.Rmd
Quitting from lines 258-279 (_main.Rmd) 
Error in dplyr::summarise(., frequency = sum(!!as.name("proportion")),  : 
  â„¹ In argument: `unique_alleles = paste0(...)`.
Caused by error in `strsplit()`:
! non-character argument
Calls: tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

**Comment by bcorrie** [comment]
Good news is, no errors on `study_id = E-MTAB-9995` and `study_id = PRJNA731610` for the repertoires I tested.

**Comment by bcorrie** [comment]
study_id = PRJNA715378 also fails with this error.

Both PRJNA715378 and PRJNA752617 from the same group/author, probably the same annotation tool/problem.

**Comment by bcorrie** [comment]
This is what a failed output looks like...
<img width="769" alt="image" src="https://github.com/airr-community/rep-cred/assets/1105216/83f46b28-3038-4c87-957e-ce08874c937e">

**Comment by williamdlees** [comment]
Brian this is enormously useful, thanks!On 15 Feb 2024, at 23:05, Brian Corrie ***@***.***> wrote:﻿
Creating a set of issues as I try repertoires from a bunch of different studies.
PRJNA752617, repertoire_id = 613b7f3eadf6058ccd849076 on covid19-1.ireceptor.org
Rendering book in directory '.'


processing file: _main.Rmd
Quitting from lines 258-279 (_main.Rmd) 
Error in dplyr::summarise(., frequency = sum(!!as.name("proportion")),  : 
  â„¹ In argument: `unique_alleles = paste0(...)`.
Caused by error in `strsplit()`:
! non-character argument
Calls: tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

**Comment by bcorrie** [comment]
This one appears to be still failing with a new error. This is true on:

Repertoire ID: 613b7f3eadf6058ccd849076
Repertoire ID: 609e9b5f8a4ef25782e2103e

```
processing file: _main.Rmd
Quitting from lines 185-228 (_main.Rmd)
Error in `dplyr::mutate()`:
ℹ In argument: `vj_not_frame = !vj_in_frame`.
Caused by error:
! object 'vj_in_frame' not found
Backtrace:
1. ... %>% ...
7. dplyr:::mutate.data.frame(...)
8. dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
10. dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
11. mask$eval_all_mutate(quo)
12. dplyr (local) eval()
Execution halted
```
Looks like failure if missing vj_in_frame data.

**Comment by ssnn-airr** [comment]
@bcorrie can you please update your repcred and test these repertoires again?

**Comment by bcorrie** [comment]
Yes, both of these are now working...
